#!/bin/bash

my_call() {
    for i in {1..10}; do
        echo "$i"
        sleep 1
    done | ./target/debug/spellcli
}


make_calls() {
    for i in {1..10}; do
        my_call &
    done
}
make_calls &
