#!/bin/bash

run_help() {
cat << EOF
Usage: ./test_several_spells -l LOOPS -c CALLS

Options:
    -l --loops LOOPS        how many loops to for each call to make
    -c --calls CALLS        how many calls to make

Notes:
this will call a func that will loop and print the curent loop iter

EOF
}

LOOPS=10
CALLS=10

while [[ -n "$1" ]]; do
    case "$1" in
        -l|--loops)
            LOOPS="$2"
            shift
            ;;
        -c|--calls)
            CALLS="$2"
            shift
            ;;
        -h|--help)
            run_help
            exit 0
            ;;
        *)
            run_help
            exit 1
            ;;
    esac
    shift
done

my_call() {
    local i
    for ((i=1; i < LOOPS + 1; i++)); do
        echo "$i"
        sleep 1
    done | ./target/debug/spellcli -s
}


make_calls() {
    local i
    for ((i=0; i < CALLS; i++)); do
        my_call &
    done
}

make_calls &
